### ISSUE TITLE
Lumina-desktop package cannot be installed on Debian Jessie

### ISSUE THREAD

**Issue by slicer69** [Nanolx/nano-packaging#1]
Today I set up a fresh installation of Debian 8 Jessie (amd64) and enabled the http://apt.nanolx.org/dists/photonic repository. I can search for files in the repository, but when I try to install the lumina-desktop package I get the following error:

Depends: libqt5core5a (>= 5.4.0) but 5.3.2+dfsg-4+deb8u1 is to be installed

I've checked and 5.3.2 is the newest version of the library in the Debian repositores. I do not believe there is a newer version in Backports.

I wonder if you would be willing to update the Lumina package so that people running Debian Stable can install it from your repo?

Update: I have built and tested Lumina on another Debian 8 machine and confirmed Lumina will run with version 5.3.2 of the libqt5core5a library, so there should not be any compatibly issue is the version requirement is lowered in the lumina-desktop package.

Thank you.

**Comment by Nanolx** [comment]
My repository is for testing/unstable (Apt sees my repo as Unstable branch), where Qt 5.4 is available. I personally don't plan to officially support stable.

Though you can grab my packaging scripts and compile packages for stable on your own.

**Comment by Nanolx** [comment]
On a side note: Qt 5.3 and 5.4 do have ABI-incompatibilities, thus dh enforces Qt 5.4 when build on unstable (the Qt version is not hardcoded in my packaging scripts).

While lumina seems fine, other Qt-dependant packages like qt5-configuration-tool for example will not work with Qt 5.4, when build with Qt 5.3 (and vice versa) and probably others, too.

**Comment by slicer69** [comment]
Thanks, I have set up my own repository using your scripts to supply Stable packages.
